**issue** name 'Config' is not defined  
**fix** Add from fastai.datasets import Config

**issue** Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/nbuser/.kaggle/kaggle.json'
403 - Forbidden  
**fix** Run ! chmod 600 /home/nbuser/.kaggle/kaggle.json

**issue** still getting 403 after accepting the terms
**fix** go to the rules page and accept the terms again
